language: php

cache: composer

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

 matrix:
   allow_failures:
    - php: hhvm

before_script:
    - ./scripts/travis-init.sh

script: ./vendor/bin/phpunit
